/*
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Availability :  IEquatable<Availability>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="Availability" /> class.
        /// </summary>
        /// <param name="_Availability">Disponibilidade do SKU.</param>
        /// <param name="PriceFrom">Preço De.</param>
        /// <param name="PriceFor">Preço Por.</param>
        public Availability(bool? _Availability = default(bool?), decimal? PriceFrom = default(decimal?), decimal? PriceFor = default(decimal?))
        {
            this._Availability = _Availability;
            this.PriceFrom = PriceFrom;
            this.PriceFor = PriceFor;
            
        }

        /// <summary>
        /// Disponibilidade do SKU
        /// </summary>
        /// <value>Disponibilidade do SKU</value>
        [DataMember(Name="availability")]
        public bool? _Availability { get; set; }
        /// <summary>
        /// Preço De
        /// </summary>
        /// <value>Preço De</value>
        [DataMember(Name="priceFrom")]
        public decimal? PriceFrom { get; set; }
        /// <summary>
        /// Preço Por
        /// </summary>
        /// <value>Preço Por</value>
        [DataMember(Name="priceFor")]
        public decimal? PriceFor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Availability {\n");
            sb.Append("  _Availability: ").Append(_Availability).Append("\n");
            sb.Append("  PriceFrom: ").Append(PriceFrom).Append("\n");
            sb.Append("  PriceFor: ").Append(PriceFor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Availability)obj);
        }

        /// <summary>
        /// Returns true if Availability instances are equal
        /// </summary>
        /// <param name="other">Instance of Availability to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Availability other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this._Availability == other._Availability ||
                    this._Availability != null &&
                    this._Availability.Equals(other._Availability)
                ) && 
                (
                    this.PriceFrom == other.PriceFrom ||
                    this.PriceFrom != null &&
                    this.PriceFrom.Equals(other.PriceFrom)
                ) && 
                (
                    this.PriceFor == other.PriceFor ||
                    this.PriceFor != null &&
                    this.PriceFor.Equals(other.PriceFor)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this._Availability != null)
                    hash = hash * 59 + this._Availability.GetHashCode();
                    if (this.PriceFrom != null)
                    hash = hash * 59 + this.PriceFrom.GetHashCode();
                    if (this.PriceFor != null)
                    hash = hash * 59 + this.PriceFor.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(Availability left, Availability right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Availability left, Availability right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
