/*
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BusinessErrorMessage :  IEquatable<BusinessErrorMessage>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessErrorMessage" /> class.
        /// </summary>
        /// <param name="Code">Código de erro..</param>
        /// <param name="Message">Mensagem de erro..</param>
        public BusinessErrorMessage(string Code = default(string), string Message = default(string))
        {
            this.Code = Code;
            this.Message = Message;
            
        }

        /// <summary>
        /// Código de erro.
        /// </summary>
        /// <value>Código de erro.</value>
        [DataMember(Name="code")]
        public string Code { get; set; }
        /// <summary>
        /// Mensagem de erro.
        /// </summary>
        /// <value>Mensagem de erro.</value>
        [DataMember(Name="message")]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessErrorMessage {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((BusinessErrorMessage)obj);
        }

        /// <summary>
        /// Returns true if BusinessErrorMessage instances are equal
        /// </summary>
        /// <param name="other">Instance of BusinessErrorMessage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessErrorMessage other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Code == other.Code ||
                    this.Code != null &&
                    this.Code.Equals(other.Code)
                ) && 
                (
                    this.Message == other.Message ||
                    this.Message != null &&
                    this.Message.Equals(other.Message)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Code != null)
                    hash = hash * 59 + this.Code.GetHashCode();
                    if (this.Message != null)
                    hash = hash * 59 + this.Message.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(BusinessErrorMessage left, BusinessErrorMessage right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BusinessErrorMessage left, BusinessErrorMessage right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
