/*
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CartShipping :  IEquatable<CartShipping>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="CartShipping" /> class.
        /// </summary>
        /// <param name="Customer">Customer (required).</param>
        /// <param name="Address">Address (required).</param>
        public CartShipping(CartShippingCustomer Customer = default(CartShippingCustomer), Address Address = default(Address))
        {
            // to ensure "Customer" is required (not null)
            if (Customer == null)
            {
                throw new InvalidDataException("Customer is a required property for CartShipping and cannot be null");
            }
            else
            {
                this.Customer = Customer;
            }
            // to ensure "Address" is required (not null)
            if (Address == null)
            {
                throw new InvalidDataException("Address is a required property for CartShipping and cannot be null");
            }
            else
            {
                this.Address = Address;
            }
            
        }

        /// <summary>
        /// Gets or Sets Customer
        /// </summary>
        [DataMember(Name="customer")]
        public CartShippingCustomer Customer { get; set; }
        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name="address")]
        public Address Address { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CartShipping {\n");
            sb.Append("  Customer: ").Append(Customer).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((CartShipping)obj);
        }

        /// <summary>
        /// Returns true if CartShipping instances are equal
        /// </summary>
        /// <param name="other">Instance of CartShipping to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CartShipping other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Customer == other.Customer ||
                    this.Customer != null &&
                    this.Customer.Equals(other.Customer)
                ) && 
                (
                    this.Address == other.Address ||
                    this.Address != null &&
                    this.Address.Equals(other.Address)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Customer != null)
                    hash = hash * 59 + this.Customer.GetHashCode();
                    if (this.Address != null)
                    hash = hash * 59 + this.Address.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(CartShipping left, CartShipping right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CartShipping left, CartShipping right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
