/*
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Features :  IEquatable<Features>
    {
                /// <summary>
        /// Tipo
        /// </summary>
        /// <value>Tipo</value>
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum COREnum for "COR"
            /// </summary>
            [EnumMember(Value = "COR")]
            COREnum,
            
            /// <summary>
            /// Enum TAMANHOEnum for "TAMANHO"
            /// </summary>
            [EnumMember(Value = "TAMANHO")]
            TAMANHOEnum,
            
            /// <summary>
            /// Enum VOLTAGEMEnum for "VOLTAGEM"
            /// </summary>
            [EnumMember(Value = "VOLTAGEM")]
            VOLTAGEMEnum,
            
            /// <summary>
            /// Enum MODELOEnum for "MODELO"
            /// </summary>
            [EnumMember(Value = "MODELO")]
            MODELOEnum,
            
            /// <summary>
            /// Enum CARACTERSTICASEnum for "CARACTERÍSTICAS"
            /// </summary>
            [EnumMember(Value = "CARACTERÍSTICAS")]
            CARACTERSTICASEnum,
            
            /// <summary>
            /// Enum ESPECIFICAESTCNICASEnum for "ESPECIFICAÇÕES TÉCNICAS"
            /// </summary>
            [EnumMember(Value = "ESPECIFICAÇÕES TÉCNICAS")]
            ESPECIFICAESTCNICASEnum
        }
        /// <summary>
        /// Tipo
        /// </summary>
        /// <value>Tipo</value>
        [DataMember(Name="type")]
        public TypeEnum? Type { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Features" /> class.
        /// </summary>
        /// <param name="Name">Nome.</param>
        /// <param name="Value">Valor.</param>
        /// <param name="Type">Tipo.</param>
        public Features(string Name = default(string), string Value = default(string), TypeEnum? Type = default(TypeEnum?))
        {
            this.Name = Name;
            this.Value = Value;
            this.Type = Type;
            
        }

        /// <summary>
        /// Nome
        /// </summary>
        /// <value>Nome</value>
        [DataMember(Name="name")]
        public string Name { get; set; }
        /// <summary>
        /// Valor
        /// </summary>
        /// <value>Valor</value>
        [DataMember(Name="value")]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Features {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Features)obj);
        }

        /// <summary>
        /// Returns true if Features instances are equal
        /// </summary>
        /// <param name="other">Instance of Features to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Features other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Value == other.Value ||
                    this.Value != null &&
                    this.Value.Equals(other.Value)
                ) && 
                (
                    this.Type == other.Type ||
                    this.Type != null &&
                    this.Type.Equals(other.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                    if (this.Value != null)
                    hash = hash * 59 + this.Value.GetHashCode();
                    if (this.Type != null)
                    hash = hash * 59 + this.Type.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(Features left, Features right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Features left, Features right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
