/*
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PurchaseAuthConversionRate :  IEquatable<PurchaseAuthConversionRate>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseAuthConversionRate" /> class.
        /// </summary>
        /// <param name="VendorId">Identificador do parceiro.</param>
        /// <param name="ConversionFactor">Fator de conversão.</param>
        public PurchaseAuthConversionRate(string VendorId = default(string), decimal? ConversionFactor = default(decimal?))
        {
            this.VendorId = VendorId;
            this.ConversionFactor = ConversionFactor;
            
        }

        /// <summary>
        /// Identificador do parceiro
        /// </summary>
        /// <value>Identificador do parceiro</value>
        [DataMember(Name="vendorId")]
        public string VendorId { get; set; }
        /// <summary>
        /// Fator de conversão
        /// </summary>
        /// <value>Fator de conversão</value>
        [DataMember(Name="conversionFactor")]
        public decimal? ConversionFactor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PurchaseAuthConversionRate {\n");
            sb.Append("  VendorId: ").Append(VendorId).Append("\n");
            sb.Append("  ConversionFactor: ").Append(ConversionFactor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((PurchaseAuthConversionRate)obj);
        }

        /// <summary>
        /// Returns true if PurchaseAuthConversionRate instances are equal
        /// </summary>
        /// <param name="other">Instance of PurchaseAuthConversionRate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PurchaseAuthConversionRate other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.VendorId == other.VendorId ||
                    this.VendorId != null &&
                    this.VendorId.Equals(other.VendorId)
                ) && 
                (
                    this.ConversionFactor == other.ConversionFactor ||
                    this.ConversionFactor != null &&
                    this.ConversionFactor.Equals(other.ConversionFactor)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.VendorId != null)
                    hash = hash * 59 + this.VendorId.GetHashCode();
                    if (this.ConversionFactor != null)
                    hash = hash * 59 + this.ConversionFactor.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(PurchaseAuthConversionRate left, PurchaseAuthConversionRate right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PurchaseAuthConversionRate left, PurchaseAuthConversionRate right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
