/*
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PurchaseCustomer :  IEquatable<PurchaseCustomer>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseCustomer" /> class.
        /// </summary>
        /// <param name="Name">Nome do cliente.</param>
        /// <param name="DocumentNumber">Documento ex: CPF, CNPJ.</param>
        /// <param name="Rg">RG.</param>
        /// <param name="Email">E-mail.</param>
        /// <param name="Address">Address.</param>
        /// <param name="Phones">Telefones.</param>
        public PurchaseCustomer(string Name = default(string), string DocumentNumber = default(string), string Rg = default(string), string Email = default(string), Address Address = default(Address), List<Phone> Phones = default(List<Phone>))
        {
            this.Name = Name;
            this.DocumentNumber = DocumentNumber;
            this.Rg = Rg;
            this.Email = Email;
            this.Address = Address;
            this.Phones = Phones;
            
        }

        /// <summary>
        /// Nome do cliente
        /// </summary>
        /// <value>Nome do cliente</value>
        [DataMember(Name="name")]
        public string Name { get; set; }
        /// <summary>
        /// Documento ex: CPF, CNPJ
        /// </summary>
        /// <value>Documento ex: CPF, CNPJ</value>
        [DataMember(Name="documentNumber")]
        public string DocumentNumber { get; set; }
        /// <summary>
        /// RG
        /// </summary>
        /// <value>RG</value>
        [DataMember(Name="rg")]
        public string Rg { get; set; }
        /// <summary>
        /// E-mail
        /// </summary>
        /// <value>E-mail</value>
        [DataMember(Name="email")]
        public string Email { get; set; }
        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name="address")]
        public Address Address { get; set; }
        /// <summary>
        /// Telefones
        /// </summary>
        /// <value>Telefones</value>
        [DataMember(Name="phones")]
        public List<Phone> Phones { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PurchaseCustomer {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DocumentNumber: ").Append(DocumentNumber).Append("\n");
            sb.Append("  Rg: ").Append(Rg).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Phones: ").Append(Phones).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((PurchaseCustomer)obj);
        }

        /// <summary>
        /// Returns true if PurchaseCustomer instances are equal
        /// </summary>
        /// <param name="other">Instance of PurchaseCustomer to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PurchaseCustomer other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.DocumentNumber == other.DocumentNumber ||
                    this.DocumentNumber != null &&
                    this.DocumentNumber.Equals(other.DocumentNumber)
                ) && 
                (
                    this.Rg == other.Rg ||
                    this.Rg != null &&
                    this.Rg.Equals(other.Rg)
                ) && 
                (
                    this.Email == other.Email ||
                    this.Email != null &&
                    this.Email.Equals(other.Email)
                ) && 
                (
                    this.Address == other.Address ||
                    this.Address != null &&
                    this.Address.Equals(other.Address)
                ) && 
                (
                    this.Phones == other.Phones ||
                    this.Phones != null &&
                    this.Phones.SequenceEqual(other.Phones)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                    if (this.DocumentNumber != null)
                    hash = hash * 59 + this.DocumentNumber.GetHashCode();
                    if (this.Rg != null)
                    hash = hash * 59 + this.Rg.GetHashCode();
                    if (this.Email != null)
                    hash = hash * 59 + this.Email.GetHashCode();
                    if (this.Address != null)
                    hash = hash * 59 + this.Address.GetHashCode();
                    if (this.Phones != null)
                    hash = hash * 59 + this.Phones.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(PurchaseCustomer left, PurchaseCustomer right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PurchaseCustomer left, PurchaseCustomer right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
