/*
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Search :  IEquatable<Search>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="Search" /> class.
        /// </summary>
        /// <param name="Products">Products.</param>
        /// <param name="Categories">Categories.</param>
        /// <param name="Brands">Brands.</param>
        /// <param name="Vendors">Vendors.</param>
        /// <param name="LowerPrice">Produtos com menor preço em pontos no resultado.</param>
        /// <param name="HigherPrice">Produtos com maior preço em pontos no resultado.</param>
        /// <param name="PageIndex">Pagina atual.</param>
        /// <param name="LastPage">Última página.</param>
        public Search(List<ProductSearch> Products = default(List<ProductSearch>), List<FilterCategory> Categories = default(List<FilterCategory>), List<ProductBrand> Brands = default(List<ProductBrand>), List<VendorSearch> Vendors = default(List<VendorSearch>), decimal? LowerPrice = default(decimal?), decimal? HigherPrice = default(decimal?), string PageIndex = default(string), string LastPage = default(string))
        {
            this.Products = Products;
            this.Categories = Categories;
            this.Brands = Brands;
            this.Vendors = Vendors;
            this.LowerPrice = LowerPrice;
            this.HigherPrice = HigherPrice;
            this.PageIndex = PageIndex;
            this.LastPage = LastPage;
            
        }

        /// <summary>
        /// Gets or Sets Products
        /// </summary>
        [DataMember(Name="products")]
        public List<ProductSearch> Products { get; set; }
        /// <summary>
        /// Gets or Sets Categories
        /// </summary>
        [DataMember(Name="categories")]
        public List<FilterCategory> Categories { get; set; }
        /// <summary>
        /// Gets or Sets Brands
        /// </summary>
        [DataMember(Name="brands")]
        public List<ProductBrand> Brands { get; set; }
        /// <summary>
        /// Gets or Sets Vendors
        /// </summary>
        [DataMember(Name="vendors")]
        public List<VendorSearch> Vendors { get; set; }
        /// <summary>
        /// Produtos com menor preço em pontos no resultado
        /// </summary>
        /// <value>Produtos com menor preço em pontos no resultado</value>
        [DataMember(Name="lowerPrice")]
        public decimal? LowerPrice { get; set; }
        /// <summary>
        /// Produtos com maior preço em pontos no resultado
        /// </summary>
        /// <value>Produtos com maior preço em pontos no resultado</value>
        [DataMember(Name="higherPrice")]
        public decimal? HigherPrice { get; set; }
        /// <summary>
        /// Pagina atual
        /// </summary>
        /// <value>Pagina atual</value>
        [DataMember(Name="pageIndex")]
        public string PageIndex { get; set; }
        /// <summary>
        /// Última página
        /// </summary>
        /// <value>Última página</value>
        [DataMember(Name="lastPage")]
        public string LastPage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Search {\n");
            sb.Append("  Products: ").Append(Products).Append("\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("  Brands: ").Append(Brands).Append("\n");
            sb.Append("  Vendors: ").Append(Vendors).Append("\n");
            sb.Append("  LowerPrice: ").Append(LowerPrice).Append("\n");
            sb.Append("  HigherPrice: ").Append(HigherPrice).Append("\n");
            sb.Append("  PageIndex: ").Append(PageIndex).Append("\n");
            sb.Append("  LastPage: ").Append(LastPage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Search)obj);
        }

        /// <summary>
        /// Returns true if Search instances are equal
        /// </summary>
        /// <param name="other">Instance of Search to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Search other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Products == other.Products ||
                    this.Products != null &&
                    this.Products.SequenceEqual(other.Products)
                ) && 
                (
                    this.Categories == other.Categories ||
                    this.Categories != null &&
                    this.Categories.SequenceEqual(other.Categories)
                ) && 
                (
                    this.Brands == other.Brands ||
                    this.Brands != null &&
                    this.Brands.SequenceEqual(other.Brands)
                ) && 
                (
                    this.Vendors == other.Vendors ||
                    this.Vendors != null &&
                    this.Vendors.SequenceEqual(other.Vendors)
                ) && 
                (
                    this.LowerPrice == other.LowerPrice ||
                    this.LowerPrice != null &&
                    this.LowerPrice.Equals(other.LowerPrice)
                ) && 
                (
                    this.HigherPrice == other.HigherPrice ||
                    this.HigherPrice != null &&
                    this.HigherPrice.Equals(other.HigherPrice)
                ) && 
                (
                    this.PageIndex == other.PageIndex ||
                    this.PageIndex != null &&
                    this.PageIndex.Equals(other.PageIndex)
                ) && 
                (
                    this.LastPage == other.LastPage ||
                    this.LastPage != null &&
                    this.LastPage.Equals(other.LastPage)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Products != null)
                    hash = hash * 59 + this.Products.GetHashCode();
                    if (this.Categories != null)
                    hash = hash * 59 + this.Categories.GetHashCode();
                    if (this.Brands != null)
                    hash = hash * 59 + this.Brands.GetHashCode();
                    if (this.Vendors != null)
                    hash = hash * 59 + this.Vendors.GetHashCode();
                    if (this.LowerPrice != null)
                    hash = hash * 59 + this.LowerPrice.GetHashCode();
                    if (this.HigherPrice != null)
                    hash = hash * 59 + this.HigherPrice.GetHashCode();
                    if (this.PageIndex != null)
                    hash = hash * 59 + this.PageIndex.GetHashCode();
                    if (this.LastPage != null)
                    hash = hash * 59 + this.LastPage.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(Search left, Search right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Search left, Search right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
