/*
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Stores :  IEquatable<Stores>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="Stores" /> class.
        /// </summary>
        /// <param name="Id">Identificador da loja.</param>
        /// <param name="Name">Nome da loja.</param>
        /// <param name="Logotype">Logotipo da loja.</param>
        /// <param name="Priority">Prioridade da loja.</param>
        /// <param name="Vendor">Vendor.</param>
        public Stores(string Id = default(string), string Name = default(string), string Logotype = default(string), decimal? Priority = default(decimal?), VendorStores Vendor = default(VendorStores))
        {
            this.Id = Id;
            this.Name = Name;
            this.Logotype = Logotype;
            this.Priority = Priority;
            this.Vendor = Vendor;
            
        }

        /// <summary>
        /// Identificador da loja
        /// </summary>
        /// <value>Identificador da loja</value>
        [DataMember(Name="id")]
        public string Id { get; set; }
        /// <summary>
        /// Nome da loja
        /// </summary>
        /// <value>Nome da loja</value>
        [DataMember(Name="name")]
        public string Name { get; set; }
        /// <summary>
        /// Logotipo da loja
        /// </summary>
        /// <value>Logotipo da loja</value>
        [DataMember(Name="logotype")]
        public string Logotype { get; set; }
        /// <summary>
        /// Prioridade da loja
        /// </summary>
        /// <value>Prioridade da loja</value>
        [DataMember(Name="priority")]
        public decimal? Priority { get; set; }
        /// <summary>
        /// Gets or Sets Vendor
        /// </summary>
        [DataMember(Name="vendor")]
        public VendorStores Vendor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Stores {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Logotype: ").Append(Logotype).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Vendor: ").Append(Vendor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Stores)obj);
        }

        /// <summary>
        /// Returns true if Stores instances are equal
        /// </summary>
        /// <param name="other">Instance of Stores to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Stores other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Logotype == other.Logotype ||
                    this.Logotype != null &&
                    this.Logotype.Equals(other.Logotype)
                ) && 
                (
                    this.Priority == other.Priority ||
                    this.Priority != null &&
                    this.Priority.Equals(other.Priority)
                ) && 
                (
                    this.Vendor == other.Vendor ||
                    this.Vendor != null &&
                    this.Vendor.Equals(other.Vendor)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                    if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                    if (this.Logotype != null)
                    hash = hash * 59 + this.Logotype.GetHashCode();
                    if (this.Priority != null)
                    hash = hash * 59 + this.Priority.GetHashCode();
                    if (this.Vendor != null)
                    hash = hash * 59 + this.Vendor.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(Stores left, Stores right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Stores left, Stores right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
