/*
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.SwaggerGen.Annotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class AutorizaoApiController : Controller
    { 

        /// <summary>
        /// Gera um token
        /// </summary>
        /// <remarks>Recurso utilizado para obter tokens de acesso</remarks>
        /// <param name="grantType"></param>
        /// <param name="campaignId"></param>
        /// <param name="user"></param>
        /// <param name="password"></param>
        /// <response code="201">Operação realizada com sucesso.</response>
        /// <response code="400">Requisição mal formada.</response>
        /// <response code="401">Não autenticado.</response>
        /// <response code="403">O acesso ao recurso foi negado.</response>
        /// <response code="404">Recurso não encontrado.</response>
        /// <response code="500">Erro Interno.</response>
        [HttpPost]
        [Route("/marketplace-api/v1/access-token")]
        [SwaggerOperation("AccessTokenPost")]
        [SwaggerResponse(200, type: typeof(Token))]
        public virtual IActionResult AccessTokenPost([FromForm]string grantType, [FromForm]string campaignId, [FromForm]string user, [FromForm]string password)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Token>(exampleJson)
            : default(Token);
            return new ObjectResult(example);
        }
    }
}
