/*
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.SwaggerGen.Annotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class ProdutoApiController : Controller
    { 

        /// <summary>
        /// Recurso utilizado para retornar informações de um determinado produto
        /// </summary>
        /// <remarks>Obtém um produto pelo SKU</remarks>
        /// <param name="productSKUId">Identificador do SKU</param>
        /// <param name="fields">Filtro para reduzir o número de atributos a ser retornado para esse recurso. Ex. _fields&#x3D;field1,field2,...fieldN</param>
        /// <response code="200">Operação realizada com sucesso.</response>
        /// <response code="400">Requisição mal formada.</response>
        /// <response code="401">Requisição requer autenticação.</response>
        /// <response code="403">O acesso ao recurso foi negado.</response>
        /// <response code="404">Recurso não encontrado.</response>
        /// <response code="422">Requisição não processável.</response>
        /// <response code="500">Erro Interno.</response>
        [HttpGet]
        [Route("/marketplace-api/v1/products/{productSKUId}")]
        [SwaggerOperation("ProductsProductSKUIdGet")]
        [SwaggerResponse(200, type: typeof(ProductDetail))]
        public virtual IActionResult ProductsProductSKUIdGet([FromRoute]string productSKUId, [FromQuery]string fields)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<ProductDetail>(exampleJson)
            : default(ProductDetail);
            return new ObjectResult(example);
        }
    }
}
